# Stage 1: Build the application
FROM node:14 as build 
WORKDIR /app
COPY . . 
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]


